name: nmfw0
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - geopandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - tslearn
  - patsy
  - nimfa
  - pip
  - pip:
      - implicit
